### PR TITLE
Feature/update to laravel nova 4

### PR DESCRIPTION
**Pull request by Nks**
Here is the update of the package to Laravel Nova v4.

The fast release would be appreciated.

Thanks.

screenshot 2022-11-25 at 01 22 44

screenshot 2022-11-25 at 01 23 31

### CODE REVIEW

**Review by LorenzoAlu — APPROVED** [review]
💣

**Comment by seanmangar** [comment]
Hey guys - will the PR be merged? Any way I can help?

**Review by Nembie — CHANGES_REQUESTED** [review]
The only thing missing is the correct configuration on the `nova.mix.js` file, after which it worked! Probably needs another check from @KasparRosin but everything seems to work!

[Check my comment here](https://github.com/outl1ne/nova-table-field/issues/6#issuecomment-1500870828)

**Comment by nathan-io** [comment]
Hi @Nks any chance you could update the PR to fix `nova.mix.js`?

**Comment by Nks** [comment]
Hey @nathan-io 

The lodash provider has been added, but I am not experiencing the problem you reported on any projects.

Also, I see that you are using the laravel-nova alias, which is unnecessary because Nova already exists in the current package as the dependency.

**Comment by nathan-io** [comment]
Thanks for the update @Nks . I re-installed the fork through Composer without issue.

While this update resolved the console errors on my end, something still seems to be broken. 

Regardless of what I input into the field, the value is saved as `null`. 

I don't see the save icons shown in your original comment. [This](https://i.gyazo.com/043427af09b1490800553994ed12543c.mp4) is what I see. So for some reason, it's just not saving the inputs.

This may have something to do with the fact that I'm using this field with the `outl1ne/nova-settings` package rather than in a standard Nova model resource. Usage example [here](https://github.com/outl1ne/nova-table-field/issues/6#issuecomment-1491180456).

It's possible that this is a separate issue.

> I see that you are using the laravel-nova alias, which is unnecessary because Nova already exists in the current package as the dependency.

I think this comment is for Nembie. See [here](https://github.com/outl1ne/nova-table-field/issues/6#issuecomment-1500870828).

**Comment by Nembie** [comment]
Hi @nathan-io, have you tried using this version in a simple Nova resource? Does it keep giving you errors in your project?
As soon as I can I also try the example you posted so as to understand if there is a conflict between the packages.

I retried the PR just to be sure and now everything is ok with no further changes 😁

P.S. I don't have the icon that was posted in the preview image either, it looks like an asynchronous data save

**Review by Nembie — APPROVED** [review]

**Comment by nathan-io** [comment]
Hi @Nembie It does appear to work correctly when I use it in a standard Nova resource, so long as the attribute is cast as an `array` type.

I still don't see the green save icons which appear in the screenshot above, but the values are indeed saved. 

https://gyazo.com/4af7d1e4f371d47a9c7cb0da8b0f1c4c

```
> App\Models\Bonus::find(4)->details
= [
    [
      "hey",
      "ya",
      "sss",
      "tt",
      "fd",
    ],
  ]
```

**Comment by Nks** [comment]
@nathan-io could you please try to install the fresh Nova and the package from the fork and test whether it works for all cases? As I said - we have been using it in our company for a while and see no issues with the package even about 10 different packages were installed, but we are not using the latest version of Nova, and I didn't test it since I proposed the PR.

**Comment by nathan-io** [comment]
We were on Nova 4.22.2. I upgraded to 4.23.0, the behavior is the same.

It seems to work fine when used in a Nova resource on an attribute that is cast as an `array`.

It's only when I use it with the `outl1ne/nova-settings` package that the value is always `null`, even with the `array` cast.

**Comment by Nembie** [comment]
@nathan-io I installed and tested the fork with the ```outl1ne/nova-settings``` package and everything seems to work fine(I didn't even cast as an array), at this point I assume there is some problem with your code or with some package you have installed.

For the icon I think @Nks has experimented with some AJAX calls because there is no trace of this functionality in the package, or at least it doesn't seem to me.

My environment:
- ```Laravel``` 10.6.2
- ```Laravel Nova```4.23.0
- ```outl1ne/nova-settings``` 5.1.0

Screenshot 2023-04-21 alle 08 35 38

**Comment by nathan-io** [comment]
Hi @Nembie I was also able to successfully use the fork with `outl1ne/nova-settings`. 

The `Trix` field was the issue, I'm just not sure why. I had a `Trix` field in the same panel along with the `Table` field. When I removed it, `Table` works.

**Comment by nathan-io** [comment]
After installing the 2.1.0 release, I tried this again and the issue seems to be resolved.

I can use the `Table` field in the same panel with a `Trix` field and save values to both.

**Comment by allantatter** [comment]
@nathan-io Great, thanks for the quick feedback!

**Pull request merged**
